-- Terms
ALTER TABLE energia.terms
ADD COLUMN is_required BOOLEAN NOT NULL DEFAULT FALSE;

-- Permissions (energia_app)

GRANT USAGE ON SCHEMA energia TO energia_app;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA energia TO energia_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA energia TO energia_app;

ALTER DEFAULT PRIVILEGES FOR USER flyway_user IN SCHEMA energia
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO energia_app;

ALTER DEFAULT PRIVILEGES FOR USER flyway_user IN SCHEMA energia
GRANT USAGE, SELECT ON SEQUENCES TO energia_app;